// <auto-generated />
using INSY7315Prototype.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INSY7315Prototype.Migrations
{
    [DbContext(typeof(KingdomCatsDb))]
    [Migration("20260726203601_SeedCats")]
    partial class SeedCats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INSY7315Prototype.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdoptionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Badge = "New Arrival",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Oliver",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob1.jpeg",
                            TagsCsv = "Cuddly,Indoor Only"
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Badge = "Staff Favorite",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Luna",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob2.jpeg",
                            TagsCsv = "Playful,Good with Dogs"
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Months",
                            Category = "Kitten",
                            Gender = "Female",
                            Name = "Mochi",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob3.jpeg",
                            TagsCsv = "Energetic,Vocal"
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = "Available",
                            AgeDisplay = "9 Years",
                            Category = "Senior",
                            Gender = "Male",
                            Name = "Whiskers",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob4.jpeg",
                            TagsCsv = "Calm,Lap Cat"
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "SpecialNeeds",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob5.jpeg",
                            TagsCsv = "Special Needs,Gentle"
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "SpecialNeeds",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob6.jpeg",
                            TagsCsv = "Special Needs,Gentle"
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "SpecialNeeds",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob7.jpeg",
                            TagsCsv = "Special Needs,Gentle"
                        },
                        new
                        {
                            Id = 8,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "SpecialNeeds",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob8.jpeg",
                            TagsCsv = "Special Needs,Gentle"
                        },
                        new
                        {
                            Id = 9,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "SpecialNeeds",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob9.jpeg",
                            TagsCsv = "Special Needs,Gentle"
                        },
                        new
                        {
                            Id = 10,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "SpecialNeeds",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob10.jpeg",
                            TagsCsv = "Special Needs,Gentle"
                        },
                        new
                        {
                            Id = 11,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "SpecialNeeds",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatsstorage.blob.core.windows.net/kingdomcatssanctuarycontainer/blob11.jpeg",
                            TagsCsv = "Special Needs,Gentle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
