// <auto-generated />
using INSY7315Prototype.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INSY7315Prototype.Migrations
{
    [DbContext(typeof(KingdomCatsDb))]
    [Migration("20260727170543_InitialCreate5")]
    partial class InitialCreate5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INSY7315Prototype.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdoptionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Badge = "New Arrival",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Oliver",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob1.jpeg",
                            TagsCsv = "Cuddly,Indoor Only"
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Badge = "Staff Favorite",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Luna",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob2.jpeg",
                            TagsCsv = "Playful,Good with Dogs"
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Months",
                            Category = "Kitten",
                            Gender = "Female",
                            Name = "Mochi",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob3.jpeg",
                            TagsCsv = "Energetic,Vocal"
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = "Available",
                            AgeDisplay = "9 Years",
                            Category = "Senior",
                            Gender = "Male",
                            Name = "Whiskers",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob4.jpeg",
                            TagsCsv = "Calm,Lap Cat"
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob5.jpeg",
                            TagsCsv = "Friendly,Gentle"
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Bella",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob6.jpeg",
                            TagsCsv = "Loving,Gentle"
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Leo",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob7.jpeg",
                            TagsCsv = "Gentle,Quiet"
                        },
                        new
                        {
                            Id = 8,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Milo",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob8.jpeg",
                            TagsCsv = "Calm,Affectionate"
                        },
                        new
                        {
                            Id = 9,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Daisy",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob9.jpeg",
                            TagsCsv = "Active,Curious"
                        },
                        new
                        {
                            Id = 10,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Charlie",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob10.jpeg",
                            TagsCsv = "Shy,Gentle"
                        },
                        new
                        {
                            Id = 11,
                            AdoptionStatus = "Available",
                            AgeDisplay = "8 Months",
                            Category = "Kitten",
                            Gender = "Female",
                            Name = "Coco",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob11.jpeg",
                            TagsCsv = "Playful,Curious"
                        },
                        new
                        {
                            Id = 12,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Badge = "Staff Favorite",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Simba",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob12.jpeg",
                            TagsCsv = "Friendly,Playful"
                        },
                        new
                        {
                            Id = 13,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Nala",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob13.jpeg",
                            TagsCsv = "Affectionate,Indoor Only"
                        },
                        new
                        {
                            Id = 14,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Years",
                            Category = "Senior",
                            Gender = "Male",
                            Name = "Tiger",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob14.jpeg",
                            TagsCsv = "Calm,Independent"
                        },
                        new
                        {
                            Id = 15,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Badge = "New Arrival",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Lily",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob15.jpeg",
                            TagsCsv = "Sweet,Playful"
                        },
                        new
                        {
                            Id = 16,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Oscar",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob16.jpeg",
                            TagsCsv = "Friendly,Lap Cat"
                        },
                        new
                        {
                            Id = 17,
                            AdoptionStatus = "Available",
                            AgeDisplay = "7 Months",
                            Category = "Kitten",
                            Gender = "Female",
                            Name = "Ruby",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob17.jpeg",
                            TagsCsv = "Energetic,Vocal"
                        },
                        new
                        {
                            Id = 18,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Jasper",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob18.jpeg",
                            TagsCsv = "Gentle,Indoor Only"
                        },
                        new
                        {
                            Id = 19,
                            AdoptionStatus = "Available",
                            AgeDisplay = "10 Years",
                            Category = "Senior",
                            Gender = "Female",
                            Name = "Rosie",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob19.jpeg",
                            TagsCsv = "Calm,Loving"
                        },
                        new
                        {
                            Id = 20,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Shadow",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob20.jpeg",
                            TagsCsv = "Quiet,Affectionate"
                        },
                        new
                        {
                            Id = 21,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Lucy",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob21.jpeg",
                            TagsCsv = "Friendly,Good with Kids"
                        },
                        new
                        {
                            Id = 22,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Max",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob22.jpeg",
                            TagsCsv = "Playful,Curious"
                        },
                        new
                        {
                            Id = 23,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Chloe",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob23.jpeg",
                            TagsCsv = "Gentle,Quiet"
                        },
                        new
                        {
                            Id = 24,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Years",
                            Category = "Senior",
                            Gender = "Male",
                            Name = "Rocky",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob24.jpeg",
                            TagsCsv = "Calm,Independent"
                        },
                        new
                        {
                            Id = 25,
                            AdoptionStatus = "Available",
                            AgeDisplay = "9 Months",
                            Badge = "New Arrival",
                            Category = "Kitten",
                            Gender = "Female",
                            Name = "Sophie",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob25.jpeg",
                            TagsCsv = "Playful,Affectionate"
                        },
                        new
                        {
                            Id = 26,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Finn",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob26.jpeg",
                            TagsCsv = "Energetic,Friendly"
                        },
                        new
                        {
                            Id = 27,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Willow",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob27.jpeg",
                            TagsCsv = "Shy,Gentle"
                        },
                        new
                        {
                            Id = 28,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Zeus",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob28.jpeg",
                            TagsCsv = "Protective,Loving"
                        },
                        new
                        {
                            Id = 29,
                            AdoptionStatus = "Available",
                            AgeDisplay = "11 Years",
                            Category = "Senior",
                            Gender = "Female",
                            Name = "Misty",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob29.jpeg",
                            TagsCsv = "Calm,Lap Cat"
                        },
                        new
                        {
                            Id = 30,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Buddy",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob30.jpeg",
                            TagsCsv = "Friendly,Active"
                        },
                        new
                        {
                            Id = 31,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Hazel",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob31.jpeg",
                            TagsCsv = "Curious,Sweet"
                        },
                        new
                        {
                            Id = 32,
                            AdoptionStatus = "Available",
                            AgeDisplay = "7 Years",
                            Category = "Senior",
                            Gender = "Male",
                            Name = "Smokey",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob32.jpeg",
                            TagsCsv = "Gentle,Quiet"
                        },
                        new
                        {
                            Id = 33,
                            AdoptionStatus = "Available",
                            AgeDisplay = "8 Months",
                            Category = "Kitten",
                            Gender = "Female",
                            Name = "Poppy",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob33.jpeg",
                            TagsCsv = "Playful,Vocal"
                        },
                        new
                        {
                            Id = 34,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Archie",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob34.jpeg",
                            TagsCsv = "Friendly,Indoor Only"
                        },
                        new
                        {
                            Id = 35,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Pepper",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob35.jpeg",
                            TagsCsv = "Affectionate,Calm"
                        },
                        new
                        {
                            Id = 36,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Years",
                            Category = "Senior",
                            Gender = "Male",
                            Name = "George",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob36.jpeg",
                            TagsCsv = "Relaxed,Gentle"
                        },
                        new
                        {
                            Id = 37,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Badge = "New Arrival",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Zoe",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob37.jpeg",
                            TagsCsv = "Friendly,Curious"
                        },
                        new
                        {
                            Id = 38,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Theo",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob38.jpeg",
                            TagsCsv = "Playful,Affectionate"
                        },
                        new
                        {
                            Id = 39,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Gender = "Female",
                            Name = "Cleo",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob39.jpeg",
                            TagsCsv = "Calm,Loving"
                        },
                        new
                        {
                            Id = 40,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Badge = "Special Needs",
                            Category = "Adult",
                            Gender = "Male",
                            Name = "Binx",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob40.jpeg",
                            TagsCsv = "Gentle,Special Needs,Indoor Only"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
