// <auto-generated />
using System;
using INSY7315Prototype.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INSY7315Prototype.Migrations
{
    [DbContext(typeof(KingdomCatsDb))]
    [Migration("20260728071559_InitialCreate7")]
    partial class InitialCreate7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INSY7315Prototype.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CatId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonationAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ParticipantEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("INSY7315Prototype.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdoptionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Badge = "New Arrival",
                            Category = "Adult",
                            Description = "Oliver is a gentle lap cat who greets every visitor with a soft headbutt. He's still settling in after arriving recently, so a calm indoor home where he can take his time will suit him best.",
                            Gender = "Male",
                            Name = "Oliver",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob1.jpeg",
                            TagsCsv = "Cuddly,Indoor Only"
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Badge = "Staff Favorite",
                            Category = "Adult",
                            Description = "Luna is the sanctuary's resident comedian, always chasing a toy or plotting her next zoomie session. She's lived alongside dogs before and gets along with them beautifully.",
                            Gender = "Female",
                            Name = "Luna",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob2.jpeg",
                            TagsCsv = "Playful,Good with Dogs"
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Months",
                            Category = "Kitten",
                            Description = "Mochi has a lot to say and isn't shy about saying it. This chatty little kitten is full of energy and would love a home with room to explore and someone to talk back to her.",
                            Gender = "Female",
                            Name = "Mochi",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob3.jpeg",
                            TagsCsv = "Energetic,Vocal"
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = "Available",
                            AgeDisplay = "9 Years",
                            Category = "Senior",
                            Description = "Whiskers has earned his relaxed lifestyle. He spends his afternoons curled up in a sunny spot and would love a quiet home where he can be someone's devoted lap companion.",
                            Gender = "Male",
                            Name = "Whiskers",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob4.jpeg",
                            TagsCsv = "Calm,Lap Cat"
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "Adult",
                            Description = "Patch is an easygoing young cat who warms up to new people almost instantly. He's gentle with handling and would be a wonderful first cat for a family.",
                            Gender = "Male",
                            Name = "Patch",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob5.jpeg",
                            TagsCsv = "Friendly,Gentle"
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Category = "Adult",
                            Description = "Bella adores affection and will happily spend hours curled beside you. She's calm, gentle, and forms deep bonds with her people quickly.",
                            Gender = "Female",
                            Name = "Bella",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob6.jpeg",
                            TagsCsv = "Loving,Gentle"
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Description = "Leo is a quiet observer who prefers a peaceful environment. He's affectionate once he trusts you, making him ideal for a calm, patient household.",
                            Gender = "Male",
                            Name = "Leo",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob7.jpeg",
                            TagsCsv = "Gentle,Quiet"
                        },
                        new
                        {
                            Id = 8,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Description = "Milo is a steady, affectionate presence, the kind of cat who checks in on you throughout the day just to make sure you're okay.",
                            Gender = "Male",
                            Name = "Milo",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob8.jpeg",
                            TagsCsv = "Calm,Affectionate"
                        },
                        new
                        {
                            Id = 9,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "Adult",
                            Description = "Daisy investigates everything: every box, every bag, every open drawer. Her curiosity and energy make her a joy to watch and a great companion for an active household.",
                            Gender = "Female",
                            Name = "Daisy",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob9.jpeg",
                            TagsCsv = "Active,Curious"
                        },
                        new
                        {
                            Id = 10,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Category = "Adult",
                            Description = "Charlie takes a little time to come out of his shell, but once he does, he's incredibly affectionate. He'd thrive with a patient adopter willing to let him set the pace.",
                            Gender = "Male",
                            Name = "Charlie",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob10.jpeg",
                            TagsCsv = "Shy,Gentle"
                        },
                        new
                        {
                            Id = 11,
                            AdoptionStatus = "Available",
                            AgeDisplay = "8 Months",
                            Category = "Kitten",
                            Description = "Coco is a bundle of playful energy who turns every toy, string, and shadow into an adventure. She'd love a home with plenty of playtime.",
                            Gender = "Female",
                            Name = "Coco",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob11.jpeg",
                            TagsCsv = "Playful,Curious"
                        },
                        new
                        {
                            Id = 12,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Badge = "Staff Favorite",
                            Category = "Adult",
                            Description = "Simba struts around the sanctuary like he owns the place, and honestly, the staff let him. Friendly, playful, and endlessly confident, he wins everyone over fast.",
                            Gender = "Male",
                            Name = "Simba",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob12.jpeg",
                            TagsCsv = "Friendly,Playful"
                        },
                        new
                        {
                            Id = 13,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Description = "Nala is a devoted, affectionate companion who loves nothing more than curling up beside her person. She should stay strictly indoors for her safety.",
                            Gender = "Female",
                            Name = "Nala",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob13.jpeg",
                            TagsCsv = "Affectionate,Indoor Only"
                        },
                        new
                        {
                            Id = 14,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Years",
                            Category = "Senior",
                            Description = "Tiger is confident and self-assured, happy to keep himself entertained but always glad for a scratch behind the ears when you're around.",
                            Gender = "Male",
                            Name = "Tiger",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob14.jpeg",
                            TagsCsv = "Calm,Independent"
                        },
                        new
                        {
                            Id = 15,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Badge = "New Arrival",
                            Category = "Adult",
                            Description = "Lily is settling into sanctuary life with a sweet, easy-going nature. She loves a good play session followed by a long nap in the sun.",
                            Gender = "Female",
                            Name = "Lily",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob15.jpeg",
                            TagsCsv = "Sweet,Playful"
                        },
                        new
                        {
                            Id = 16,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Description = "Oscar is a certified lap cat, the moment you sit down, he's there. Friendly and affectionate, he thrives on close company.",
                            Gender = "Male",
                            Name = "Oscar",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob16.jpeg",
                            TagsCsv = "Friendly,Lap Cat"
                        },
                        new
                        {
                            Id = 17,
                            AdoptionStatus = "Available",
                            AgeDisplay = "7 Months",
                            Category = "Kitten",
                            Description = "Ruby is a lively little kitten with a big voice and even bigger personality. She'll keep you entertained and on your toes.",
                            Gender = "Female",
                            Name = "Ruby",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob17.jpeg",
                            TagsCsv = "Energetic,Vocal"
                        },
                        new
                        {
                            Id = 18,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Category = "Adult",
                            Description = "Jasper is a gentle soul who enjoys a slow-paced life of naps, gentle pets, and window watching. He should remain an indoor-only cat.",
                            Gender = "Male",
                            Name = "Jasper",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob18.jpeg",
                            TagsCsv = "Gentle,Indoor Only"
                        },
                        new
                        {
                            Id = 19,
                            AdoptionStatus = "Available",
                            AgeDisplay = "10 Years",
                            Category = "Senior",
                            Description = "Rosie is a warm, loving senior who has so much affection left to give. She'd be perfectly content spending her golden years in a quiet, loving home.",
                            Gender = "Female",
                            Name = "Rosie",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob19.jpeg",
                            TagsCsv = "Calm,Loving"
                        },
                        new
                        {
                            Id = 20,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Category = "Adult",
                            Description = "Shadow lives up to his name, often found quietly following his favorite people from room to room. He's affectionate in his own understated way.",
                            Gender = "Male",
                            Name = "Shadow",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob20.jpeg",
                            TagsCsv = "Quiet,Affectionate"
                        },
                        new
                        {
                            Id = 21,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Description = "Lucy is patient, gentle, and great with children, making her a wonderful fit for a family looking to add a friendly, easy-going cat to the household.",
                            Gender = "Female",
                            Name = "Lucy",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob21.jpeg",
                            TagsCsv = "Friendly,Good with Kids"
                        },
                        new
                        {
                            Id = 22,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Description = "Max never really grew out of his kitten phase, he's still endlessly playful and curious about everything happening around him.",
                            Gender = "Male",
                            Name = "Max",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob22.jpeg",
                            TagsCsv = "Playful,Curious"
                        },
                        new
                        {
                            Id = 23,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Category = "Adult",
                            Description = "Chloe is soft-spoken and gentle, preferring a calm environment where she can quietly enjoy her people's company without too much commotion.",
                            Gender = "Female",
                            Name = "Chloe",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob23.jpeg",
                            TagsCsv = "Gentle,Quiet"
                        },
                        new
                        {
                            Id = 24,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Years",
                            Category = "Senior",
                            Description = "Rocky is calm, self-reliant, and content to observe the world at his own pace. He'd suit an adopter who appreciates a low-maintenance, dignified companion.",
                            Gender = "Male",
                            Name = "Rocky",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob24.jpeg",
                            TagsCsv = "Calm,Independent"
                        },
                        new
                        {
                            Id = 25,
                            AdoptionStatus = "Available",
                            AgeDisplay = "9 Months",
                            Badge = "New Arrival",
                            Category = "Kitten",
                            Description = "Sophie recently joined the sanctuary and has quickly become a favorite for her playful antics and affectionate cuddles after playtime wears her out.",
                            Gender = "Female",
                            Name = "Sophie",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob25.jpeg",
                            TagsCsv = "Playful,Affectionate"
                        },
                        new
                        {
                            Id = 26,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Description = "Finn has energy to spare and a friendly nature to match. He loves interactive toys and would do best with an adopter ready for some daily play.",
                            Gender = "Male",
                            Name = "Finn",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob26.jpeg",
                            TagsCsv = "Energetic,Friendly"
                        },
                        new
                        {
                            Id = 27,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Category = "Adult",
                            Description = "Willow is a little reserved at first, but underneath the shyness is a gentle, loving cat who blossoms with a patient, quiet companion.",
                            Gender = "Female",
                            Name = "Willow",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob27.jpeg",
                            TagsCsv = "Shy,Gentle"
                        },
                        new
                        {
                            Id = 28,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Description = "Zeus is deeply loyal and a little protective of the people he loves. Once he's bonded with you, he's an affectionate shadow by your side.",
                            Gender = "Male",
                            Name = "Zeus",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob28.jpeg",
                            TagsCsv = "Protective,Loving"
                        },
                        new
                        {
                            Id = 29,
                            AdoptionStatus = "Available",
                            AgeDisplay = "11 Years",
                            Category = "Senior",
                            Description = "Misty is a serene senior lady who asks for little more than a warm lap and a gentle hand. She's calm, easy, and endlessly sweet.",
                            Gender = "Female",
                            Name = "Misty",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob29.jpeg",
                            TagsCsv = "Calm,Lap Cat"
                        },
                        new
                        {
                            Id = 30,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Category = "Adult",
                            Description = "Buddy is friendly, active, and always up for an adventure around the sanctuary. He'd love a home with space to run and explore.",
                            Gender = "Male",
                            Name = "Buddy",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob30.jpeg",
                            TagsCsv = "Friendly,Active"
                        },
                        new
                        {
                            Id = 31,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Description = "Hazel is endlessly curious and sweet-natured, the kind of cat who wants to know what's in every bag you bring through the door.",
                            Gender = "Female",
                            Name = "Hazel",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob31.jpeg",
                            TagsCsv = "Curious,Sweet"
                        },
                        new
                        {
                            Id = 32,
                            AdoptionStatus = "Available",
                            AgeDisplay = "7 Years",
                            Category = "Senior",
                            Description = "Smokey is a gentle, quiet gentleman who enjoys peaceful company and a comfortable spot to watch the world go by.",
                            Gender = "Male",
                            Name = "Smokey",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob32.jpeg",
                            TagsCsv = "Gentle,Quiet"
                        },
                        new
                        {
                            Id = 33,
                            AdoptionStatus = "Available",
                            AgeDisplay = "8 Months",
                            Category = "Kitten",
                            Description = "Poppy is a playful chatterbox who narrates her day in a series of chirps and meows. She'd love a home full of toys and conversation.",
                            Gender = "Female",
                            Name = "Poppy",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob33.jpeg",
                            TagsCsv = "Playful,Vocal"
                        },
                        new
                        {
                            Id = 34,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Category = "Adult",
                            Description = "Archie is a friendly, sociable cat who loves greeting visitors at the door. He should live strictly indoors for his own safety.",
                            Gender = "Male",
                            Name = "Archie",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob34.jpeg",
                            TagsCsv = "Friendly,Indoor Only"
                        },
                        new
                        {
                            Id = 35,
                            AdoptionStatus = "Available",
                            AgeDisplay = "4 Years",
                            Category = "Adult",
                            Description = "Pepper is calm and deeply affectionate, happiest when she's pressed up against you soaking in some quiet attention.",
                            Gender = "Female",
                            Name = "Pepper",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob35.jpeg",
                            TagsCsv = "Affectionate,Calm"
                        },
                        new
                        {
                            Id = 36,
                            AdoptionStatus = "Available",
                            AgeDisplay = "6 Years",
                            Category = "Senior",
                            Description = "George is easygoing and gentle, with a laid-back charm that makes him a comforting presence in any home.",
                            Gender = "Male",
                            Name = "George",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob36.jpeg",
                            TagsCsv = "Relaxed,Gentle"
                        },
                        new
                        {
                            Id = 37,
                            AdoptionStatus = "Available",
                            AgeDisplay = "1 Year",
                            Badge = "New Arrival",
                            Category = "Adult",
                            Description = "Zoe is a friendly newcomer with an inquisitive streak, always the first to investigate a new toy or a new face at the sanctuary.",
                            Gender = "Female",
                            Name = "Zoe",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob37.jpeg",
                            TagsCsv = "Friendly,Curious"
                        },
                        new
                        {
                            Id = 38,
                            AdoptionStatus = "Available",
                            AgeDisplay = "2 Years",
                            Category = "Adult",
                            Description = "Theo balances playful energy with genuine affection, happy to chase a toy one minute and curl up for cuddles the next.",
                            Gender = "Male",
                            Name = "Theo",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob38.jpeg",
                            TagsCsv = "Playful,Affectionate"
                        },
                        new
                        {
                            Id = 39,
                            AdoptionStatus = "Available",
                            AgeDisplay = "5 Years",
                            Category = "Adult",
                            Description = "Cleo is a calm, loving presence who forms strong bonds with her favorite people and enjoys a quiet, settled routine.",
                            Gender = "Female",
                            Name = "Cleo",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob39.jpeg",
                            TagsCsv = "Calm,Loving"
                        },
                        new
                        {
                            Id = 40,
                            AdoptionStatus = "Available",
                            AgeDisplay = "3 Years",
                            Badge = "Special Needs",
                            Category = "Adult",
                            Description = "Binx has some special needs that mean he thrives best in a calm, dedicated indoor home. He's gentle and deeply grateful for the extra care and patience of the right adopter.",
                            Gender = "Male",
                            Name = "Binx",
                            PhotoUrl = "https://kingdomcatstorage.blob.core.windows.net/catprofile/blob40.jpeg",
                            TagsCsv = "Gentle,Special Needs,Indoor Only"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
